# Generated by Django 2.2.17 on 2020-11-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('SUR', 'Survey'), ('DIS', 'Discussion'), ('DIA', 'Diary')], default='SUR', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('LIV', 'Live'), ('ARC', 'Archived')], default='PEN', max_length=3)),
            ],
        ),
    ]
