# Generated by Django 2.2.17 on 2020-11-10 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inclingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inclingapp.Tile'),
            preserve_default=False,
        ),
    ]
